version: "3.0"
services:
  postgres:
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    command: bash -c "bundle exec rake assets:precompile && bundle exec puma -C config/puma.rb"
    environment:
      PORT: 9918
      RAILS_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_SERVE_STATIC_FILES: "true"
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:7918:7918"
    depends_on:
      - postgres